### PR TITLE
Add IPTables Rule Chain to allow custom polocies

### PR DESCRIPTION
**Pull request by alwinmarkcf**
Cattle then only manges the creation of the chain and leaves the chain
itself unmanaged, so customers are able to add their rules by themself.

This is needed for customers using lowcost hoster without having an
dedicated own network.
(so its possible for example to allow access to the complete host or certain ports for certain IPs)

As we are using it already in production for our self, you can get the complete image at:
https://hub.docker.com/r/crowdfox/rancher-network-manager/ 

fixes rancher/rancher#10387

### CODE REVIEW

**Comment by alwinmarkcf** [comment]
@leodotcloud could you please review this one? As rancher silently changed the behaviour and now takes care to be on spot one, this opens a security issues for many users of rancher1.6 / cattle as many of us used a DockerPreChain which is now not working any more.

This means now every service is exposed to the outside which should just be viewable to some internal services when you are not running  on private networks or you don't have dedicated internal networks.

Without this PR there is no way to solve this issue so the security leak stays open while most of the clients might not be aware of this, as it took quite some time for our self to close this issue.

As you see there are already people building stuff on this fork and there are tons of comments on the corresponding issue.

**Comment by leodotcloud** [comment]
Thank you @alwinmarkcf for the PR. I will look into the issue.

**Comment by marvinwankersteen** [comment]
When and in which version will be this fix available? This is really important.

**Comment by cjellick** [comment]
Is this still relevant? Even though it's old, seems like it could be.
I'm going to close due to age, but feel free to reopen if you think it's still relevant. Thanks!

**Pull request closed without merging**
