### PR TITLE
fix build error

### PR DESCRIPTION
**Pull request by kingsd041**
https://github.com/rancher/rancher/issues/9917

### CODE REVIEW

**Comment by yasker** [comment]
@kingsd041 

Please add bug URL in the commit message, as well as the build failure message.

**Comment by kingsd041** [comment]
Bug URL: 
https://github.com/rancher/rancher/issues/7583

Build failure message:
```
events/event_router.go:44:2: redundant if ...; err != nil check, just return error instead.
events/event_router.go:54:2: redundant if ...; err != nil check, just return error instead.
FATA[0058] exit status 1
```

**Comment by yasker** [comment]
@kingsd041 I meant, you need to put this information in the git commit message. Otherwise, it's hard to tell what's wrong with `git log`.

**Comment by cjellick** [comment]
I don't get this build error locally nor do I see it in my test PR: 
- https://github.com/rancher/plugin-manager/pull/99
- https://drone.rancher.io/rancher/plugin-manager/245

I wonder what's going on

**Comment by leodotcloud** [comment]
@kingsd041 @cjellick @yasker https://github.com/rancher/rancher/issues/7583 is already fixed with PR: https://github.com/rancher/plugin-manager/pull/85. I don't understand what's going on here.
@kingsd041 what version of Go are you using and how are you doing the build?

**Comment by niusmallnan** [comment]
@cjellick 
This is because `golint` adds new detection rules, here: https://github.com/golang/lint/commit/e5d664e
I guess drone does not use the latest `golint`,  or probably because of the image layer cache.

@leodotcloud 
I think @kingsd041 gave a wrong URL, #9917 is right.

@yasker @kingsd041 ^^^

**Comment by yasker** [comment]
Yeah, I can reproduce the issue in the a brand new environment.

**Comment by leodotcloud** [comment]
LGTM

**Comment by cjellick** [comment]
OK, that's what I wanted to know because to me that seems like a flaw in our build system.
Basically, we have a build that is not 100% consistently reproducible.

**Comment by leodotcloud** [comment]
Created https://github.com/rancher/rancher/issues/9928 to track the build issue.

**Pull request merged**
