### PR TITLE
Parse local network by environment uuid

### PR DESCRIPTION
**Pull request by niusmallnan**
Plse see https://github.com/rancher/rancher/issues/8535

### CODE REVIEW

**Comment by leodotcloud** [comment]
@niusmallnan Logic looks good. If you can confirm that testing both ipsec and calico worked with these changes, you are good to go.

**Comment by niusmallnan** [comment]
@leodotcloud Tested both ipsec and calico, they work fine.
I have built a test setup with backported patches applied.
Calico: http://54.223.92.159:8082/env/1a7/infra/hosts
IPSec: http://54.223.92.159:8082/env/1a5/infra/hosts

**Comment by leodotcloud** [comment]
Can't access the URLs. But LGTM.
Ping @ibuildthecloud.

**Comment by niusmallnan** [comment]
Sorry, I should use AWS US.
Here, new URLs:
Calico: http://54.68.177.99:8080/env/1a7/infra/hosts
IPSec: http://54.68.177.99:8080/env/1a5/infra/hosts

**Comment by leodotcloud** [comment]
LGTM.

**Pull request merged**
